### ISSUE TITLE
Хотелось бы кнопку возврата на главную страницу 

### ISSUE THREAD

**Issue by AigSh** [fotuka/plugin#14]
![image](https://user-images.githubusercontent.com/92096123/184338559-8ac93fb0-e372-4017-a3c7-fa6e8cb19cf3.png)

**Comment by fotuka** [comment]
на главную страницу это где четыре кнопки по середине? кнопки слева это одно и то же

**Comment by MikkoArtik** [comment]
> на главную страницу это где четыре кнопки по середине? кнопки слева это одно и то же

согласен с @fotuka. Тут оставить все как есть, логика плагина предусматривает переключение между виджетами конфигурациями разных сеток

**Comment by AigSh** [comment]
все, поняла, сорян. от того, что не отображаются картинки и подписи кнопок, было непонятно сразу.
