### ISSUE TITLE
Лишние кнопки

### ISSUE THREAD

**Issue by MikkoArtik** [fotuka/plugin#20]
Нужны ли эти кнопки. Я бы их убрал
![image](https://user-images.githubusercontent.com/22727630/184524621-66b7e702-2a52-4005-b525-f670fcb57121.png)

**Comment by fotuka** [comment]
То есть, имеешь в виду, чтобы по кнопке применить, как сейчас, появлялся слой, а когда нужно закрыть плагин нажимать крестик сверху?

**Comment by MikkoArtik** [comment]
> То есть, имеешь в виду, чтобы по кнопке применить, как сейчас, появлялся слой, а когда нужно закрыть плагин нажимать крестик сверху?

ага. такой вот минимализм)
