### ISSUE TITLE
Может я делаю что-то не так, но у меня не получается shp с расстановкой

### ISSUE THREAD

**Issue by AigSh** [fotuka/plugin#32]
![image](https://user-images.githubusercontent.com/92096123/185045611-ac156bbb-7778-41c2-8edd-12dd2f59b2ff.png)
![image](https://user-images.githubusercontent.com/92096123/185045662-79af8f99-4450-4904-ae1b-2c7d83fe8803.png)

**Comment by fotuka** [comment]
почему не получается? не создается?

**Comment by AigSh** [comment]
вот на втором скрине то, что получается. и в проекте и в папке не создается шейп

**Comment by fotuka** [comment]
увидел, понял

**Comment by fotuka** [comment]
а когда наводишь мышкой на воскл. знак, что пишет?

**Comment by AigSh** [comment]
когда наводишь ничего, а при нажатии вот 
![image](https://user-images.githubusercontent.com/92096123/185049294-eb24b3d2-bbec-4736-9b1c-d37856c38410.png)
